package com.studypartner.utils;

public enum FileType {
	FILE_TYPE_FOLDER,
	FILE_TYPE_IMAGE,
	FILE_TYPE_VIDEO,
	FILE_TYPE_TEXT,
	FILE_TYPE_APPLICATION,
	FILE_TYPE_AUDIO,
	FILE_TYPE_LINK,
	FILE_TYPE_OTHER
}