name: Automatic Issue Assignment

on:
  schedule: 
    # cron job which runs every 5 minutes
    - cron: '*/5 * * * *'
  issue_comment:
    # Upon issue creation
    types: [created]
    
jobs:
  slash_assign:
    # If the acton was triggered by a new comment that starts with `/assign`
    # or a on a schedule
    if: >
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/assign')) ||
      github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Assign the user or unassign stale assignments
        uses: JasonEtco/slash-assign-action@v0.0.3
        with:
          assigned_label: assigned
          # Number of days until warning is given is 7 by default
          days_until_unassign: 15
          stale_assignment_label: open
    
